Ldb/ldb_mvc1/Models/Db.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using System.Text;
using Microsoft.AspNetCore.Hosting;

namespace ldb_mvc1.Models
{
    public class db
    {
        #region Properties

        #endregion

        #region Costructor

        #endregion

        #region Fuctions
        public void Connection()
        {
            try
            {
                SqlConnectionStringBuilder builder = new SqlConnectionStringBuilder();

                builder.DataSource= "etechenterprises.database.windows.net";
                builder.UserID = "Ravenone1";
                builder.Password = "Supersix1!";
                builder.InitialCatalog = "ldb";

                SqlConnection connection = new SqlConnection(builder.ConnectionString);
                connection.Open();

                StringBuilder sb = new StringBuilder();
                sb.Append("");
                string sql = sb.ToString();

                SqlCommand command = new SqlCommand(sql, connection);
                SqlDataReader reader = command.ExecuteReader();
                    while(reader.Read())
                {
                    Console.WriteLine(reader.GetString(0), reader.GetString(1));
                }
            }
            catch (SqlException e)
            {
                Console.WriteLine(e.ToString());
            }
        }
        #endregion

    }


}

Ldb/ldb_mvc1/Models/ErrorViewModel.cs
using System;

namespace ldb_mvc1.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Ldb/ldb_mvc1/Models/UserProfile.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ldb_mvc1.Models
{
    public class UserProfile
    {
        [Key]
        public int id { get; set; }

        [Required(ErrorMessage ="Enter First Name")]
        [Display(Name ="YoungGodz")]
        public string firstName { get; set; }

        public string middleName { get; set; }
        
        [Required(ErrorMessage ="Enter Last Name")]
        public string lastName { get; set; }

        public string sex { get; set; }

        [Required(ErrorMessage = "Enter Date of Birth ")]
        [DisplayName("Birthday")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode =true,DataFormatString ="{0:dd/MM/yyyy}")]
        public DateTime dob { get; set; }

        public int age { get; set; }
        public int phone { get; set; }

        [Required(ErrorMessage = "Enter a Valid Email")]
        public string email { get; set; }
        public int department { get; set; }
        public string userPictureUrl { get; set; }

        public List<UserProfile> ShowAllUserProfiles { get; set; }

       
    }
}

Ldb/ldb_mvc1/Controllers/CustomController.cs
using System;

using System.Collections.Generic;

using System.Linq;
using System.Security.Cryptography.Xml;
using System.Web;
using ldb_mvc1.Controllers.DataAccess;
using ldb_mvc1.Models;
using Microsoft.AspNetCore.Mvc;

namespace ldb_mvc1.Controllers
{
    public class CustomController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

         [HttpGet]
         public ActionResult InsertUserProfile()
        {
            return View();
        }

        [HttpPost]
        public ActionResult InsertUserProfile(UserProfile user)
        {
            user.dob = Convert.ToDateTime(user.dob);
            if (ModelState.IsValid)
            {
                DataAccessLayer db = new DataAccessLayer();
                string result = db.Insert(user);
                ViewData["result"] = result;
                ModelState.Clear();
                return View();
            }
            else
            {
                ModelState.AddModelError("", "Error saving data");
                return View();
            }
        }
        
        [HttpGet]
        public ActionResult ShowAllUserProfiles()
        {
            UserProfile user = new UserProfile();
            DataAccessLayer db = new DataAccessLayer();
            user.ShowAllUserProfiles = db.RetrieveProfiles();
            return View(user);

        }

        [HttpGet]
        public ActionResult Edit(int ID)
        {
            UserProfile user = new UserProfile();
            DataAccessLayer db = new DataAccessLayer();
            return View(db.RetrieveById(ID));
        }

        [HttpPost]
        public ActionResult Edit(UserProfile user)
        {
            user.dob = Convert.ToDateTime(user.dob);
            if(ModelState.IsValid)
            {
                DataAccessLayer db = new DataAccessLayer();
                string result = db.Update(user);
                ViewData["result"] = result;
                ModelState.Clear();
                return View();
            }
            else
            {
                ModelState.AddModelError("", "error in saving data");
                return View();
            }
        }
       [HttpGet]
       [Route("/CustomController/Delete",Name ="Delte_Get)")]
        public ActionResult Delete(int user_id)
        {
            /*int id = Convert.ToInt32(user_id);*/
            DataAccessLayer db = new DataAccessLayer();
            UserProfile user = new UserProfile();
            return View(db.RetrieveById(user_id));
        }

        [HttpPost]
        [Route("/CustomController/Delete", Name = "Delete_Post")]
        public ActionResult Delete(string user_id)
        {
            int id = Convert.ToInt32(user_id);
            DataAccessLayer db = new DataAccessLayer();
            string result = db.DeleteData(id);
            ViewData["result"] = result+id.ToString();
            ModelState.Clear();
            return View();

        }

    }
}

Ldb/ldb_mvc1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ldb_mvc1.Models;

namespace ldb_mvc1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Ldb/ldb_mvc1/Views/Custom/Delete.cshtml
@model ldb_mvc1.Models.UserProfile

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>UserProfile</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.firstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.firstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.middleName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.middleName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.lastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.lastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.sex)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.sex)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.dob)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.dob)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.age)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.phone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.department)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.department)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.userPictureUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.userPictureUrl)
        </dd>
    </dl>
    @ViewData["result"];
    @{Dictionary<string,string> user = new Dictionary<string, string>
        {
          {"user_id","2" }
        }; }
    <form asp-controller="Custom" asp-all-route-data=user asp-action="Delete" >
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="ShowAllUserProfiles" asp-controller="Custom">Back to List</a>
    </form>
</div>
</body>
</html>

Ldb/ldb_mvc1/Views/Custom/Edit.cshtml
@model ldb_mvc1.Models.UserProfile

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>UserProfile</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="id" class="control-label"></label>
                <input asp-for="id" class="form-control" />
                <span asp-validation-for="id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="firstName" class="control-label"></label>
                <input asp-for="firstName" class="form-control" />
                <span asp-validation-for="firstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="middleName" class="control-label"></label>
                <input asp-for="middleName" class="form-control" />
                <span asp-validation-for="middleName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="lastName" class="control-label"></label>
                <input asp-for="lastName" class="form-control" />
                <span asp-validation-for="lastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="sex" class="control-label"></label>
                <input asp-for="sex" class="form-control" />
                <span asp-validation-for="sex" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="dob" class="control-label"></label>
                <input asp-for="dob" class="form-control" />
                <span asp-validation-for="dob" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="age" class="control-label"></label>
                <input asp-for="age" class="form-control" />
                <span asp-validation-for="age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="phone" class="control-label"></label>
                <input asp-for="phone" class="form-control" />
                <span asp-validation-for="phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="email" class="control-label"></label>
                <input asp-for="email" class="form-control" />
                <span asp-validation-for="email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="department" class="control-label"></label>
                <input asp-for="department" class="form-control" />
                <span asp-validation-for="department" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="userPictureUrl" class="control-label"></label>
                <input asp-for="userPictureUrl" class="form-control" />
                <span asp-validation-for="userPictureUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Ldb/ldb_mvc1/Views/Custom/InsertUserProfile.cshtml
@model ldb_mvc1.Models.UserProfile

@{
    ViewData["Title"] = "InsertUserProfile";
}

<h1>InsertUserProfile</h1>

<h4>UserProfile</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="InsertUserProfile">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
                <label asp-for="id" class="control-label"></label>
                <input asp-for="id" class="form-control" />
                <span asp-validation-for="id" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <p>*required</p>
                <label asp-for="firstName" class="control-label"></label><p>*</p>
                <input asp-for="firstName" class="form-control" />
                <span asp-validation-for="firstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="middleName" class="control-label"></label>
                <input asp-for="middleName" class="form-control" />
                <span asp-validation-for="middleName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="lastName" class="control-label"></label><p>*</p>
                <input asp-for="lastName" class="form-control" />
                <span asp-validation-for="lastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="sex" class="control-label"></label>
                <input asp-for="sex" class="form-control" />
                <span asp-validation-for="sex" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="dob" class="control-label"></label><p>*</p>
                <input asp-for="dob" class="form-control" />
                <span asp-validation-for="dob" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="age" class="control-label"></label>
                <input asp-for="age" class="form-control" />
                <span asp-validation-for="age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="phone" class="control-label"></label>
                <input asp-for="phone" class="form-control" />
                <span asp-validation-for="phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="email" class="control-label"></label><p>*</p>
                <input asp-for="email" class="form-control" />
                <span asp-validation-for="email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="department" class="control-label"></label>
                <input asp-for="department" class="form-control" />
                <span asp-validation-for="department" class="text-danger"></span>
            </div>
         @*   <div class="form-group">
                <label asp-for="userPictureUrl" class="control-label"></label>
                <input asp-for="userPictureUrl" class="form-control" />
                <span asp-validation-for="userPictureUrl" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    @Html.ActionLink("Back","Index","Home",null,new { @class = "btn btn-primary btn-large" })
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Ldb/ldb_mvc1/Views/Custom/ShowAllUserProfiles.cshtml
@model ldb_mvc1.Models.UserProfile

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ShowAllUserProfiles</title>
</head>
<body>
<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.firstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.middleName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.lastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.sex)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.dob)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.age)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.phone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.department)
            </th>
          
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.ShowAllUserProfiles) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.firstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.middleName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.lastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.sex)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.dob)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.age)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.department)
            </td>
        
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.id },"Home") 
                @Html.ActionLink("Details", "Details", new { id = item.id },"Home") 
                @Html.ActionLink("Delete", "Delete", new { user_id = item.id },"Custom")
            </td>
        </tr>
}
    </tbody>
</table>
</body>
</html>

Ldb/ldb_mvc1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Bagabaris!</h1>
    @Html.ActionLink("Register", "InsertUserProfile", "Custom", null, new { @class="btn btn-primary btn-large"})
    @Html.ActionLink("View Members","ShowAllUserProfiles","Custom",null,new { @class="btn btn-primary btn-large"})
    @Html.ActionLink("Edit A Record","Edit","Custom",null,new {@class="btn btn-primary btn-large" })
    @Html.ActionLink("Delete A Record","Delete","Custom",null,new { @class="btn btn-primary btn-large"})

    
</div>

Ldb/ldb_mvc1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ldb_mvc1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ldb_mvc1</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ldb_mvc1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>